version: '2'

services:
  testableapi2:
    image: swaggerapi/petstore
    # ports:
    #  - "8088:8080"
    expose:
     - "8080"
    environment:
     - SWAGGER_HOST=http://petstore.swagger.io
     - SWAGGER_URL=http://localhost:8080
     - SWAGGER_BASE_PATH=/v2
  
  jmeter:
    #image: justb4/jmeter
    build:
        context: .
        dockerfile: Dockerfile-jmeter
    command: -Dlog_level.jmeter=DEBUG -Jhost=testableapi2 -Jport=8080 -n -t /mnt/input/PetApi.jmx -l /tmp/lpwd/PetApi.jtl -j /tmp/lpwd/jmeter_PetApi.log -e -o /tmp/lpwd/PetApi
    volumes:
     - .:/mnt/input:ro
     - ./jmeterdata:/tmp/lpwd:rw
